version: '3.8'
services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ziraat-app-db
      MYSQL_USER: ziraat-app-user1
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
